import numpy as np
n=int(input("Enter number of students"))
marks = np.random.randint(1,101,(n,10))
print("Original array:\n", marks)
cleared_all = np.sum(np.sum(marks>=35, axis=1)==10)
failures_per_subject = np.sum(marks<=35, axis=0)
most_failed_subject = np.argmax(failures_per_subject)
above_80 = np.where(marks.mean(axis=0)>80)
max_in_subject = marks.max(axis=0)
who_got = marks.argmax(axis=0)
sub_avg = marks.mean(axis=0)

print("\nNumber of students who have cleared all the subjects:", cleared_all)
print("\nNumber of failures in each subject:", failures_per_subject)
print("\nSubject with most failures:", most_failed_subject)
print("\nMarks for those who scored above 80%:", above_80)
print("\nMaximum marks in each subject:", max_in_subject)
print("\nWho got maximum marks:", who_got+1)
print("\nSubject Avg:", sub_avg)
